version: '3'
services:
  database:
    image: mysql/mysql-server:8.0
    ports:
      - '3309:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '123123'
      MYSQL_DATABASE: 'encurtador'
      MYSQL_USER: 'spring'
      MYSQL_PASSWORD: '123123'
    volumes:
      - './database:/var/lib/mysql'