spring:
  datasource:
    url: jdbc:mysql://database:3306/encurtador
    username: spring
    password: 123123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    problemdetails:
      enabled: true
