spring:
  datasource:
    url: "jdbc:mysql://localhost:3309/encurtador"
    username: spring
    password: 123123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
